/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package braindrainlearninggame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author luisp
 */
public class EnterPlayerNames extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement statement;

    /**
     * Creates new form EnterPlayerNames
     */
    public EnterPlayerNames() {
        initComponents();
        setSize(765, 408);
        txtP1Name.setBackground(new java.awt.Color (0,0,0,1));
        txtP2Name.setBackground(new java.awt.Color (0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtP1Name = new javax.swing.JTextField();
        lblP1Name = new javax.swing.JLabel();
        txtP2Name = new javax.swing.JTextField();
        lblP2Name = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter Player Names");
        getContentPane().setLayout(null);

        txtP1Name.setForeground(new java.awt.Color(255, 255, 255));
        txtP1Name.setBorder(null);
        txtP1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP1NameActionPerformed(evt);
            }
        });
        getContentPane().add(txtP1Name);
        txtP1Name.setBounds(222, 130, 90, 16);

        lblP1Name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/EnterP1Name (1).png"))); // NOI18N
        getContentPane().add(lblP1Name);
        lblP1Name.setBounds(140, 90, 180, 80);

        txtP2Name.setForeground(new java.awt.Color(0, 0, 0));
        txtP2Name.setBorder(null);
        txtP2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP2NameActionPerformed(evt);
            }
        });
        getContentPane().add(txtP2Name);
        txtP2Name.setBounds(460, 132, 90, 16);

        lblP2Name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/EnterP2Name (1).png"))); // NOI18N
        getContentPane().add(lblP2Name);
        lblP2Name.setBounds(380, 90, 180, 80);

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/clear (1).png"))); // NOI18N
        btnClear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClear.setContentAreaFilled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(360, 210, 90, 40);

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/okay (1).png"))); // NOI18N
        btnOk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOk.setContentAreaFilled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(210, 210, 90, 40);

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/Background (1).png"))); // NOI18N
        lblBackGround.setText("Enter Player Names");
        getContentPane().add(lblBackGround);
        lblBackGround.setBounds(0, 0, 740, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        PlayerNames pn = new PlayerNames();
        
        if(txtP1Name.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Player 1 Name", "Required Name", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(txtP2Name.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Player 2 Name", "Required Name", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/braindrain", "root", "");
            
            // Prepare SQL statement for insertion
            String query = "INSERT INTO players (names) VALUES (?)";
            PreparedStatement statement = conn.prepareStatement(query);
            
            // Insert player 1 name
            statement.setString(1, txtP1Name.getText());
            statement.executeUpdate();
            
            // Insert player 2 name
            statement.setString(1, txtP2Name.getText());
            statement.executeUpdate();
            
            // Close connection
            conn.close();
            
            // Proceed to open next frame or perform further actions
            
            pn.setP1Name(txtP1Name.getText());
            pn.setP2Name(txtP2Name.getText());
            BrainDrainLearningGame bdlg = new BrainDrainLearningGame(pn); 
            bdlg.setVisible(true);
            dispose();
            }catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: Name should be unique", "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        } 
        
        
        
    }//GEN-LAST:event_btnOkActionPerformed

    private void txtP2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP2NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP2NameActionPerformed

    private void txtP1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP1NameActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtP1Name.setText("");
        txtP2Name.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterPlayerNames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblP1Name;
    private javax.swing.JLabel lblP2Name;
    private javax.swing.JTextField txtP1Name;
    private javax.swing.JTextField txtP2Name;
    // End of variables declaration//GEN-END:variables
}
