/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package braindrainlearninggame;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.util.ArrayList;
/**
 *
 * @author Piolo Enriquez
 */
public class Leaderboard extends javax.swing.JFrame {
    
    private Object model;
    Connection con;
    Statement st;
    ArrayList<Profile> students = new ArrayList<>(); 

    public Leaderboard() {
        initComponents();
        fetch();
    }
    
    private void populateLeaderboard() {
        DefaultTableModel model = (DefaultTableModel) tblLeaderboard.getModel();
        model.setRowCount(0); // Clear existing data

            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/braindrain", "root", "")) 
            {
              String query = "SELECT PlayerName, Score FROM leaderboard ORDER BY Score DESC"; // Removed Rank column
              PreparedStatement statement = conn.prepareStatement(query);
              ResultSet rs = statement.executeQuery();

                while (rs.next()) {
                String name = rs.getString("PlayerName");
                int score = rs.getInt("Score");
                model.addRow(new Object[]{name, score}); // Removed rank from the array
              }

              conn.close();
            } catch (SQLException e) {
              e.printStackTrace();
              // Handle database connection errors gracefully
            }
    }
    
    public static void addEntry(String playerName, int score) {
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/braindrain", "root", "")) {
            String query = "INSERT INTO leaderboard (PlayerName, Score) VALUES (?, ?)";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, playerName);
            statement.setInt(2, score);
            statement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.print("Error Connection");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLeaderboard = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLeaderboard = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(765, 408));
        setResizable(false);
        setSize(new java.awt.Dimension(765, 408));
        getContentPane().setLayout(null);

        lblLeaderboard.setText("leaderboard");
        getContentPane().add(lblLeaderboard);
        lblLeaderboard.setBounds(270, 30, 280, 40);

        tblLeaderboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PlayerName", "Score", "Rank"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLeaderboard);
        if (tblLeaderboard.getColumnModel().getColumnCount() > 0) {
            tblLeaderboard.getColumnModel().getColumn(0).setResizable(false);
            tblLeaderboard.getColumnModel().getColumn(1).setResizable(false);
            tblLeaderboard.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 100, 452, 280);
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 760, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaderboard().setVisible(true);
            }
        });
    }

private void fetch() {
 DefaultTableModel model1 = (DefaultTableModel) tblLeaderboard.getModel();
 model1.setRowCount(0); 
        try 
        {
            
               Class.forName("com.mysql.cj.jdbc.Driver");
               con = DriverManager.getConnection("jdbc:mysql://localhost:3306/braindrain", "root", ""); //localhost port, databasename, username, password
            
               String sql = "select * from tblstudents";
               st = con.createStatement();
               
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) 
            {
                Profile user = new Profile(rs.getString("playerName"), rs.getString("Score")); //Calling the Students class
                Profile.add(user);
            }
            DefaultTableModel model2 = (DefaultTableModel) tblLeaderboard.getModel();
            for ( Profile user : students) { //
            Object[] row = new Object[4];
            row[0] = user.getPlayerName();
            row[1] = user.getScore();
            model2.addRow(row);
            }
        } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Leaderboard.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLeaderboard;
    private javax.swing.JTable tblLeaderboard;
    // End of variables declaration//GEN-END:variables
}
