/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package braindrainlearninggame;

/**
 *
 * @author luisp
 */
public class QuestionAnswerInitializer {
    public static QuestionAnswerChecker[] initializePairs() {
        return new QuestionAnswerChecker[] {
            new QuestionAnswerChecker("What is the capital of France?", "Paris"),
            new QuestionAnswerChecker("How many continents are there?", "7"),
            new QuestionAnswerChecker("Who wrote 'Romeo and Juliet'?", "William Shakespeare"),
            new QuestionAnswerChecker("What is the chemical symbol for water?", "H2O"),
            new QuestionAnswerChecker("What is the capital of Australia?", "Canberra"),
            new QuestionAnswerChecker("What is the largest ocean on Earth?", "Pacific"),
            new QuestionAnswerChecker("What is the chemical symbol for gold?", "Au"),
            new QuestionAnswerChecker("What is the 6th planet in our solar system?", "Saturn"),
            new QuestionAnswerChecker("What is the tallest mountain in the world?", "Mount Everest"),
            new QuestionAnswerChecker("What is the largest mammal?", "Blue Whale"),
            new QuestionAnswerChecker("What is the currency of Japan?", "Yen"),
            new QuestionAnswerChecker("What is the freezing point of water in Celsius?", "0"),
            new QuestionAnswerChecker("What is the largest planet in our solar system?", "Jupiter"),
            new QuestionAnswerChecker("Who painted the Mona Lisa?", "Leonardo da Vinci"),
            new QuestionAnswerChecker("What is the national animal of China?", "Giant Panda"),
            new QuestionAnswerChecker("What is the speed of light in a vacuum?", "299,792,458 m/s"),
            new QuestionAnswerChecker("What is the chemical symbol for oxygen?", "O"),
            new QuestionAnswerChecker("Who invented the telephone?", "Alexander Graham Bell"),
            new QuestionAnswerChecker("What is the largest desert in the world?", "Sahara"),
            new QuestionAnswerChecker("What is the boiling point of water in Celsius?", "100"),
            new QuestionAnswerChecker("What is the currency of the United Kingdom?", "Pound Sterling"),
            new QuestionAnswerChecker("What is the smallest country in the world?", "Vatican City"),
            new QuestionAnswerChecker("What is the chemical symbol for silver?", "Ag"),
            new QuestionAnswerChecker("Who discovered penicillin?", "Alexander Fleming"),
            new QuestionAnswerChecker("What is the largest river in the world?", "Amazon"),
            new QuestionAnswerChecker("What is the national flower of Japan?", "Cherry Blossom"),
            new QuestionAnswerChecker("What is the powerhouse of the cell?", "Mitochondria"),
            new QuestionAnswerChecker("What is the largest bird in the world?", "Ostrich"),
            new QuestionAnswerChecker("Who wrote 'To Kill a Mockingbird'?", "Harper Lee"),
            new QuestionAnswerChecker("What is the chemical symbol for carbon?", "C"),
            new QuestionAnswerChecker("What is the fastest land animal?", "Cheetah"),
            new QuestionAnswerChecker("What is the capital of Brazil?", "Brasília"),
            new QuestionAnswerChecker("What is the largest moon of Saturn?", "Titan"),
            new QuestionAnswerChecker("Who composed 'Moonlight Sonata'?", "Ludwig van Beethoven"),
            new QuestionAnswerChecker("What is the chemical symbol for iron?", "Fe"),
            new QuestionAnswerChecker("What is the longest river in Europe?", "Volga"),
            new QuestionAnswerChecker("What is the national sport of Canada?", "Ice Hockey"),
            new QuestionAnswerChecker("What is the largest continent?", "Asia"),
            new QuestionAnswerChecker("What is the smallest planet in our solar system?", "Mercury"),
            new QuestionAnswerChecker("Who discovered America?", "Christopher Columbus"),
            new QuestionAnswerChecker("What is the capital of Russia?", "Moscow"),
            new QuestionAnswerChecker("What is the national flower of India?", "Lotus"),
            new QuestionAnswerChecker("What is the chemical symbol for sodium?", "Na"),
            new QuestionAnswerChecker("Who wrote '1984'?", "George Orwell"),
            new QuestionAnswerChecker("What is the currency of China?", "Renminbi"),
            new QuestionAnswerChecker("What is the largest island in the world?", "Greenland"),
            new QuestionAnswerChecker("What is the hottest planet in our solar system?", "Venus"),
            new QuestionAnswerChecker("Who was the first man to step on the moon?", "Neil Armstrong"),
            new QuestionAnswerChecker("What is the capital of Spain?", "Madrid"),
            new QuestionAnswerChecker("What is the chemical symbol for helium?", "He"),
            new QuestionAnswerChecker("What is the largest tree species in the world?", "Sequoia"),
            new QuestionAnswerChecker("Who painted 'Starry Night'?", "Vincent van Gogh"),
            new QuestionAnswerChecker("What is the national animal of Canada?", "Beaver"),
            new QuestionAnswerChecker("What is the largest fish in the world?", "Whale Shark"),
            new QuestionAnswerChecker("What is the currency of Australia?", "Australian Dollar"),
            new QuestionAnswerChecker("What is the chemical symbol for nitrogen?", "N"),
            new QuestionAnswerChecker("Who wrote 'Pride and Prejudice'?", "Jane Austen"),
            new QuestionAnswerChecker("What is the speed of sound in air?", "343 m/s"),
            new QuestionAnswerChecker("What is the highest mountain range in the world?", "Himalayas"),
            new QuestionAnswerChecker("What is the national bird of the United States?", "Bald Eagle"),
            new QuestionAnswerChecker("What is the chemical symbol for calcium?", "Ca"),
            new QuestionAnswerChecker("Who discovered the theory of relativity?", "Albert Einstein"),
            new QuestionAnswerChecker("What is the largest lake in Africa?", "Victoria"),
            new QuestionAnswerChecker("What is the national flower of France?", "Iris"),
            new QuestionAnswerChecker("What is the currency of Brazil?", "Real"),
            new QuestionAnswerChecker("What is the chemical symbol for potassium?", "K"),
            new QuestionAnswerChecker("Who wrote 'The Great Gatsby'?", "Scott Fitzgerald"),
            new QuestionAnswerChecker("What is the largest volcano in the solar system?", "Olympus Mons"),
            new QuestionAnswerChecker("What is the national animal of Australia?", "Kangaroo"),
            new QuestionAnswerChecker("What is the currency of Canada?", "Canadian Dollar"),
            new QuestionAnswerChecker("What is the chemical symbol for tin?", "Sn"),
            new QuestionAnswerChecker("Who painted the ceiling of the Sistine Chapel?", "Leonardo da Vinci"),
            new QuestionAnswerChecker("What is the fastest bird in the world?", "Peregrine Falcon"),
            new QuestionAnswerChecker("What is the capital of Italy?", "Rome"),
            new QuestionAnswerChecker("What is the chemical symbol for copper?", "Cu"),
            new QuestionAnswerChecker("Who discovered gravity?", "Isaac Newton"),
            new QuestionAnswerChecker("What is the largest planet in our solar system?", "Jupiter"),
            new QuestionAnswerChecker("What is the national flower of the United States?", "Rose"),
            new QuestionAnswerChecker("What is the chemical symbol for uranium?", "U"),
            new QuestionAnswerChecker("Who wrote 'Hamlet'?", "William Shakespeare"),
            new QuestionAnswerChecker("What is the highest waterfall in the world?", "Angel Falls"),
            new QuestionAnswerChecker("What is the national animal of India?", "Bengal Tiger"),
            new QuestionAnswerChecker("What is the currency of India?", "Rupee"),
            new QuestionAnswerChecker("What is the chemical symbol for lead?", "Pb"),
            new QuestionAnswerChecker("Who discovered electricity?", "Benjamin Franklin"),
            new QuestionAnswerChecker("What is the largest lake in the world by surface area?", "Superior"),
            new QuestionAnswerChecker("What is the national sport of Japan?", "Sumo Wrestling"),
            new QuestionAnswerChecker("What is the currency of Germany?", "Euro"),
            new QuestionAnswerChecker("What is the chemical symbol for mercury?", "Hg"),
            new QuestionAnswerChecker("Who painted the 'Last Supper'?", "Leonardo da Vinci"),
            new QuestionAnswerChecker("What is the largest mammal in the ocean?", "Blue Whale"),
            new QuestionAnswerChecker("What is the capital of China?", "Beijing"),
            new QuestionAnswerChecker("What is the chemical symbol for silicon?", "Si"),
            new QuestionAnswerChecker("Who discovered the theory of evolution?", "Charles Darwin"),
            new QuestionAnswerChecker("What is the highest mountain in North America?", "Denali"),
            new QuestionAnswerChecker("What is the national flower of China?", "Plum Blossom"),
            new QuestionAnswerChecker("What is the currency of France?", "Euro"),
            new QuestionAnswerChecker("What is the chemical symbol for magnesium?", "Mg"),
            new QuestionAnswerChecker("Who wrote 'The Catcher in the Rye'?", "J.D. Salinger"),
            new QuestionAnswerChecker("Who is the National Hero of the Philippines?", "Dr. Jose Rizal"),
            new QuestionAnswerChecker("Who is the Brain of the Katipunan?", "Emilio Jacinto"),
            new QuestionAnswerChecker("What is the capital of Philippines?", "Manila"),
            new QuestionAnswerChecker("Who is the father of the Filipino language?", "Manuel Quezon"),
            new QuestionAnswerChecker("What is the highest mountain in the Philippines?", "Mount Apo"),
            new QuestionAnswerChecker("Who was the first president of the Philippines?", "Emillio Aguinaldo"),
            new QuestionAnswerChecker("What does NCR mean?", "National Capital Region"),
            new QuestionAnswerChecker("When does the Philippines celebrate its independence day?", "June 12"),
            new QuestionAnswerChecker("What is the national flower of Philippines", "Sampaguita"),
            new QuestionAnswerChecker("Who is the Filipino hero known for winning the Battle of Mactan?", "Lapu-Lapu"),
            new QuestionAnswerChecker("Which Filipino hero led the 1896 Philippine Revolution?", "Andres Bonifacio"),
            new QuestionAnswerChecker("What is the largest provincial capital in Luzon in terms of land area?", "Ilagan City"),
            new QuestionAnswerChecker("This island province is the smallest province in the Philippines in terms of land area and population.", "Batanes"),
            new QuestionAnswerChecker("Pangasinan is found in what part of the Philippines?", "Manila"),
            new QuestionAnswerChecker("What is the \"Summer Capital\" of the Philippines?", "Baguio City"),
            new QuestionAnswerChecker("How many provinces are there in Philippines?", "Baguio City"),
            new QuestionAnswerChecker(" What is the capital of Ilocos Norte?", "Laoag City"),
            new QuestionAnswerChecker("What is the oldest city of the Philippines?", "Cebu"),
            new QuestionAnswerChecker("What is the largest island of the Philippine Archipelago?", "Luzon")
        };
    }
}
